---
- name: Check if '{{ dependency_apt_repo__repo }}' is not empty
  assert:
    that: (dependency_apt_repo__repo | length) > 0

- name: Ensure state '{{ dependency_apt_repo__state | capitalize }}' for the repository '{{ dependency_apt_repo__repo }}'
  apt_repository:
    repo: "{{ dependency_apt_repo__repo }}"
    mode: "{{ dependency_apt_repo__mode }}"
    state: "{{ dependency_apt_repo__state }}"
    update_cache: "{{ dependency_apt_repo__update_cache }}"
    validate_certs: "{{ dependency_apt_repo__validate_certs }}"
