---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition)
docker__edition: 'ce'
docker__package:
  - "docker-{{ docker__edition }}"

docker__apt_release_channel: stable
docker__apt_arch: amd64
docker__apt_repository: "deb [arch={{ docker__apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker__apt_release_channel }}"
docker__apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# Docker Compose options
docker__install_compose: true
docker__compose_url: https://github.com/docker/compose/releases/download/{{ docker__compose_version }}/docker-compose-Linux-x86_64
docker__compose_path: /usr/local/bin/docker-compose
