---
- name: Check if '{{ dependency_apt_key__url }}' is not empty
  assert:
    that: (dependency_apt_key__url | length) > 0

- name: Ensure state '{{ dependency_apt_key__state | capitalize }}' for the apt key - '{{ dependency_apt_key__url }}'
  apt_key:
    url: "{{ dependency_apt_key__url }}"
    state: "{{ dependency_apt_key__state }}"
    validate_certs: "{{ dependency_apt_key__validate_certs }}"
