---
- name: Add apt key - {{ apt__key_url }}
  apt_key:
    url: '{{ apt__key_url }}'
    state: '{{ dependency_apt_key__key_state }}'
    validate_certs: '{{ dependency_apt_key__repo_validate_certs }}'
