---
- name: "Create symlink for keytool"
  file:
    src: "{{ java_openjdk__java_home }}/bin/keytool"
    dest: "/usr/bin/keytool"
    owner: "{{ java_openjdk__java_security_owner }}"
    group: "{{ java_openjdk__java_security_group }}"
    state: "link"

- name: Add JAVA_HOME in /etc/environment
  lineinfile:
    path: /etc/environment
    regexp: "^export JAVA_HOME="
    line: "export JAVA_HOME={{ java_openjdk__java_home }}"
    state: present
