---

- name: 'Check current docker-compose version'
  command: docker-compose --version
  register: docker_setup__compose_current_version
  changed_when: false
  failed_when: false

- name: 'Delete existing docker-compose version'
  file:
    path: "{{ docker_setup__compose_path }}"
    state: absent
  when: >
    docker_setup__compose_current_version.stdout is defined
    and docker_setup__compose_version not in docker_setup__compose_current_version.stdout

- name: 'Install Docker Compose (if configured)'
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_setup__compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_setup__compose_path }}"
    mode: 0755