---

dependencies:
  - name: 'dependency-apt'
    apt__packages: '{{ docker_setup__old_packages }}'
    apt__state: 'absent'

  - name: 'dependency-apt-key'
    apt__key_url: '{{ docker_setup__apt_gpg_key }}'

  - name: 'dependency-apt-repo'
    apt__repo_repository: '{{ docker_setup__apt_repository }}'

  - name: 'dependency-apt'
    apt__packages: '{{ docker_setup__dependencies }}'

  - name: 'dependency-apt'
    apt__packages: '{{ docker_setup__package }}'
    notify: 'restart docker'