---
dependencies:
  - name: "dependency-apt"
    dependency_apt__packages: "{{ docker__old_packages }}"
    dependency_apt__state: "absent"

  - name: "dependency-apt-key"
    dependency_apt_key__url: "{{ docker__apt_gpg_key }}"

  - name: "dependency-apt-repo"
    dependency_apt_repo__repo: "{{ docker__apt_repository }}"

  - name: 'dependency-apt'
    dependency_apt__packages: "{{ docker__dependencies }}"

  - name: "dependency-apt"
    dependency_apt__packages: "{{ docker__package }}"
    notify: "restart docker"
